In [2]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [3]:
df=pd.read_csv('Binanary.csv')

In [4]:
df.head()

   GPA Grade  TUCE Grade  PSI  Grade Letter Grade
0       2.66          20    0      0            C
1       2.89          22    0      0            B
2       3.28          24    0      0            B
3       2.92          12    0      0            B
4       4.00          21    0      1            A

In [13]:
y=df['Grade']
y.head()

0    0
1    0
2    0
3    0
4    1
Name: Grade, dtype: int64

In [12]:
x=df[['GPA Grade','TUCE Grade','PSI']]
x.head()

   GPA Grade  TUCE Grade  PSI
0       2.66          20    0
1       2.89          22    0
2       3.28          24    0
3       2.92          12    0
4       4.00          21    0

In [14]:
logit_model=LogisticRegression
logit_model.fit(x,y)

AttributeError: 'DataFrame' object has no attribute '_validate_params'