# Soft Drink Analysis

In [1]:
import random
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt

### Creat Contingency table from the data frame
pd.crosstab(index=df['Country'], columns=df['Product'])

### another way of doing this is
import this
### from scipy.stats.contingency import crosstab

In [2]:
from scipy.stats.contingency import crosstab

In [3]:
a = ['A', 'B', 'A', 'A', 'B', 'B', 'A', 'A', 'B', 'B']

x = ['X', 'X', 'X', 'Y', 'Z', 'Z', 'Y', 'Y', 'Z', 'Z']

In [4]:
(avals, xvals), count = crosstab(a, x)
avals

array(['A', 'B'], dtype='<U1')

In [5]:
xvals

array(['X', 'Y', 'Z'], dtype='<U1')

In [6]:
count

array([[2, 3, 0],
       [1, 0, 4]])

In [7]:
df = pd.read_csv('soft_drink.csv')

In [8]:
df.head()

           Name                       Email  Status  Current State Next State
0  Naimur Munna      naimurmunna1@gmail.com  Student     Coca Cola         RC
1   Md Neaz Ali         neazali77@gmail.com  Student        Sprite  Coca Cola
2      HR ANTOR           antorhr@gmail.com  Student     Coca Cola  Coca Cola
3         Nayem           nkiu016@gmail.com  Student        Sprite      Pepsi
4       Shakib   shakibrahman1122@gmail.com  Student     Coca Cola     Sprite

In [9]:
df['Next State'].head()

0           RC
1    Coca Cola
2    Coca Cola
3        Pepsi
4       Sprite
Name: Next State, dtype: object

In [10]:
df['Current State'].head()

0    Coca Cola
1       Sprite
2    Coca Cola
3       Sprite
4    Coca Cola
Name: Current State, dtype: object

# The contingency Table is okay but not the TPM

In [11]:
tpm = pd.crosstab(index=df['Current State'], columns=df['Next State'])
tpm

Next State     Coca Cola  Pepsi  RC  Sprite
Current State
Coca Cola             14     12   3      16
Pepsi                  1      0   0       0
RC                     1      0   1       0
Sprite                 7      2   2       1

In [12]:
np.sum(tpm,1)

Current State
Coca Cola    45
Pepsi         1
RC            2
Sprite       12
dtype: int64

In [13]:
tpm/(np.sum(tpm,1))

Next State     Coca Cola  Pepsi   RC    Sprite
Current State
Coca Cola       0.311111   12.0  1.5  1.333333
Pepsi           0.022222    0.0  0.0  0.000000
RC              0.022222    0.0  0.5  0.000000
Sprite          0.155556    2.0  1.0  0.083333

In [14]:
TPM = round(tpm/np.sum(tpm,1),2)
TPM

Next State     Coca Cola  Pepsi   RC  Sprite
Current State
Coca Cola           0.31   12.0  1.5    1.33
Pepsi               0.02    0.0  0.0    0.00
RC                  0.02    0.0  0.5    0.00
Sprite              0.16    2.0  1.0    0.08

In [15]:
np.matmul(TPM,TPM)

Next State     Coca Cola  Pepsi     RC  Sprite
Current State
Coca Cola         0.5789   6.38  2.545  0.5187
Pepsi             0.0062   0.24  0.030  0.0266
RC                0.0162   0.24  0.280  0.0266
Sprite            0.1224   2.08  0.820  0.2192

In [16]:
ans = TPM
ans

Next State     Coca Cola  Pepsi   RC  Sprite
Current State
Coca Cola           0.31   12.0  1.5    1.33
Pepsi               0.02    0.0  0.0    0.00
RC                  0.02    0.0  0.5    0.00
Sprite              0.16    2.0  1.0    0.08

### for 10 days anslysis 
### what is p(X10=1)=?

In [17]:
n = 10
for i in range(n):
    ans = np.matmul(ans,TPM)
ans

Next State     Coca Cola     Pepsi        RC    Sprite
Current State
Coca Cola       0.395736  6.056572  2.468962  0.586358
Pepsi           0.008096  0.123847  0.050494  0.011988
RC              0.016565  0.253415  0.103424  0.024532
Sprite          0.107011  1.637381  0.667668  0.158509

## For 100 days

In [18]:
ans = TPM
for i in range(100):
    ans = np.matmul(ans,TPM)
ans

Next State     Coca Cola     Pepsi        RC    Sprite
Current State
Coca Cola       0.052647  0.805601  0.328480  0.077989
Pepsi           0.001077  0.016477  0.006719  0.001595
RC              0.002204  0.033719  0.013749  0.003264
Sprite          0.014235  0.217823  0.088816  0.021087

In [19]:
type(ans)

pandas.core.frame.DataFrame

In [20]:
ans['RC']['Pepsi']

0.006718515489641413

In [21]:
ans

Next State     Coca Cola     Pepsi        RC    Sprite
Current State
Coca Cola       0.052647  0.805601  0.328480  0.077989
Pepsi           0.001077  0.016477  0.006719  0.001595
RC              0.002204  0.033719  0.013749  0.003264
Sprite          0.014235  0.217823  0.088816  0.021087

In [22]:
TPM["Coca Cola"]

Current State
Coca Cola    0.31
Pepsi        0.02
RC           0.02
Sprite       0.16
Name: Coca Cola, dtype: float64

In [23]:
TPM["Coca Cola"]["Coca Cola"]

0.31

In [24]:
TPM

Next State     Coca Cola  Pepsi   RC  Sprite
Current State
Coca Cola           0.31   12.0  1.5    1.33
Pepsi               0.02    0.0  0.0    0.00
RC                  0.02    0.0  0.5    0.00
Sprite              0.16    2.0  1.0    0.08

In [25]:
s1 = input("Enter Your initial State: \n")
s2 = input("Enter Your Final State: \n")
TPM[s1][s2]

Enter Your initial State:

Enter Your Final State:

KeyError: ''

In [ ]:
tpm

In [ ]:
rowSums = np.sum(tpm,1)
rowSums

In [ ]:
sum(rowSums)

In [26]:
tpm/rowSums

NameError: name 'rowSums' is not defined

In [27]:
np.flip(rowSums)

NameError: name 'rowSums' is not defined

In [28]:
rowsums = np.array(rowSums)

NameError: name 'rowSums' is not defined

In [29]:
rowsums

NameError: name 'rowsums' is not defined

In [30]:
tpm

Next State     Coca Cola  Pepsi  RC  Sprite
Current State
Coca Cola             14     12   3      16
Pepsi                  1      0   0       0
RC                     1      0   1       0
Sprite                 7      2   2       1

In [31]:
rowsums

NameError: name 'rowsums' is not defined

In [32]:
tpm/rowsums

NameError: name 'rowsums' is not defined

In [33]:
rowsums.reshape(1,4)

NameError: name 'rowsums' is not defined

In [34]:
rowsums.shape

NameError: name 'rowsums' is not defined

In [35]:
rowsums = rowsums.reshape(1,4)

NameError: name 'rowsums' is not defined

In [36]:
tpm/rowsums

NameError: name 'rowsums' is not defined

In [37]:
rowsums

NameError: name 'rowsums' is not defined

In [38]:
tpm['Coca Cola'][:]/rowsums[0][0]

NameError: name 'rowsums' is not defined

In [39]:
tpm['Pepsi'][:]/rowsums[0][]

SyntaxError: invalid syntax (150355903.py, line 1)

In [40]:
rowsums[0][1]

NameError: name 'rowsums' is not defined

In [89]:
rowsums

array([[45,  1,  2, 12]])

In [90]:
rowsums[0][2]

2

In [91]:
rowsums[0][3]

12

In [93]:
tpm['RC']/rowsums[0][2]

Current State
Coca Cola    1.5
Pepsi        0.0
RC           0.5
Sprite       1.0
Name: RC, dtype: float64

In [94]:
tpm

Next State     Coca Cola  Pepsi  RC  Sprite
Current State
Coca Cola             14     12   3      16
Pepsi                  1      0   0       0
RC                     1      0   1       0
Sprite                 7      2   2       1