In [3]:
import random
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("soft_drink.csv")

In [5]:
df.head()

           Name                       Email  Status  Current State Next State
0  Naimur Munna      naimurmunna1@gmail.com  Student     Coca Cola         RC
1   Md Neaz Ali         neazali77@gmail.com  Student        Sprite  Coca Cola
2      HR ANTOR           antorhr@gmail.com  Student     Coca Cola  Coca Cola
3         Nayem           nkiu016@gmail.com  Student        Sprite      Pepsi
4       Shakib   shakibrahman1122@gmail.com  Student     Coca Cola     Sprite

In [6]:
tpm = pd.crosstab(df['Current State'],df['Next State'])
tpm

Next State     Coca Cola  Pepsi  RC  Sprite
Current State
Coca Cola             14     12   3      16
Pepsi                  1      0   0       0
RC                     1      0   1       0
Sprite                 7      2   2       1

In [7]:
df.head()

           Name                       Email  Status  Current State Next State
0  Naimur Munna      naimurmunna1@gmail.com  Student     Coca Cola         RC
1   Md Neaz Ali         neazali77@gmail.com  Student        Sprite  Coca Cola
2      HR ANTOR           antorhr@gmail.com  Student     Coca Cola  Coca Cola
3         Nayem           nkiu016@gmail.com  Student        Sprite      Pepsi
4       Shakib   shakibrahman1122@gmail.com  Student     Coca Cola     Sprite

In [9]:
cstate = df.head()

In [10]:
cstate

           Name                       Email  Status  Current State Next State
0  Naimur Munna      naimurmunna1@gmail.com  Student     Coca Cola         RC
1   Md Neaz Ali         neazali77@gmail.com  Student        Sprite  Coca Cola
2      HR ANTOR           antorhr@gmail.com  Student     Coca Cola  Coca Cola
3         Nayem           nkiu016@gmail.com  Student        Sprite      Pepsi
4       Shakib   shakibrahman1122@gmail.com  Student     Coca Cola     Sprite

In [13]:
cstate = df['Current State']
nstate = df['Next State']

In [14]:
cstate.head()

0    Coca Cola
1       Sprite
2    Coca Cola
3       Sprite
4    Coca Cola
Name: Current State, dtype: object

In [15]:
len(nstate)

60

In [18]:
tpm = pd.crosstab(cstate,nstate)
tpm

Next State     Coca Cola  Pepsi  RC  Sprite
Current State
Coca Cola             14     12   3      16
Pepsi                  1      0   0       0
RC                     1      0   1       0
Sprite                 7      2   2       1

In [19]:
type(tpm)

pandas.core.frame.DataFrame

In [20]:
tpm2 = np.array(tpm)

In [21]:
tpm2

array([[14, 12,  3, 16],
       [ 1,  0,  0,  0],
       [ 1,  0,  1,  0],
       [ 7,  2,  2,  1]])

In [22]:
type(tpm2)

numpy.ndarray

In [23]:
tpm2.ndim

2

In [24]:
sms = np.sum(tpm2,1)

In [25]:
sms

array([45,  1,  2, 12])

In [26]:
tpm2/sms

array([[ 0.31111111, 12.        ,  1.5       ,  1.33333333],
       [ 0.02222222,  0.        ,  0.        ,  0.        ],
       [ 0.02222222,  0.        ,  0.5       ,  0.        ],
       [ 0.15555556,  2.        ,  1.        ,  0.08333333]])

In [27]:
sms.reshape(4,1)

array([[45],
       [ 1],
       [ 2],
       [12]])

In [28]:
tpm2/sms

array([[ 0.31111111, 12.        ,  1.5       ,  1.33333333],
       [ 0.02222222,  0.        ,  0.        ,  0.        ],
       [ 0.02222222,  0.        ,  0.5       ,  0.        ],
       [ 0.15555556,  2.        ,  1.        ,  0.08333333]])

In [30]:
tpm2[0,2]

3

In [34]:
np.sum(tpm2,1)

array([45,  1,  2, 12])

In [35]:
sms

array([45,  1,  2, 12])

In [36]:
tpm2

array([[14, 12,  3, 16],
       [ 1,  0,  0,  0],
       [ 1,  0,  1,  0],
       [ 7,  2,  2,  1]])

In [37]:
tpm2/sms

array([[ 0.31111111, 12.        ,  1.5       ,  1.33333333],
       [ 0.02222222,  0.        ,  0.        ,  0.        ],
       [ 0.02222222,  0.        ,  0.5       ,  0.        ],
       [ 0.15555556,  2.        ,  1.        ,  0.08333333]])

In [39]:
TPM = tpm2.transpose()/sms

In [43]:
TPM.transpose().sum(1)

array([1., 1., 1., 1.])

In [46]:
TPM = TPM.transpose()
TPM

array([[0.31111111, 0.26666667, 0.06666667, 0.35555556],
       [1.        , 0.        , 0.        , 0.        ],
       [0.5       , 0.        , 0.5       , 0.        ],
       [0.58333333, 0.16666667, 0.16666667, 0.08333333]])

In [48]:
np.matmul(TPM,TPM)

array([[0.60419753, 0.14222222, 0.11333333, 0.14024691],
       [0.31111111, 0.26666667, 0.06666667, 0.35555556],
       [0.40555556, 0.13333333, 0.28333333, 0.17777778],
       [0.48009259, 0.16944444, 0.13611111, 0.21435185]])

In [50]:
temp = TPM
n = 10
for i in range(n):
    temp = np.matmul(temp,TPM)
temp

array([[0.50454943, 0.16719427, 0.13250547, 0.19575083],
       [0.50469162, 0.1671503 , 0.13249904, 0.19565904],
       [0.50458835, 0.16714653, 0.13258405, 0.19568106],
       [0.50459438, 0.16717259, 0.13252096, 0.19571208]])

In [52]:
TPM

array([[0.31111111, 0.26666667, 0.06666667, 0.35555556],
       [1.        , 0.        , 0.        , 0.        ],
       [0.5       , 0.        , 0.5       , 0.        ],
       [0.58333333, 0.16666667, 0.16666667, 0.08333333]])

In [60]:
n = 20
tem3 = TPM
for i in range(0,n):
    tem3 = np.matmul(tem3,TPM)
tem3

array([[0.50458715, 0.16717635, 0.13251784, 0.19571866],
       [0.50458718, 0.16717635, 0.13251784, 0.19571864],
       [0.50458716, 0.16717635, 0.13251785, 0.19571865],
       [0.50458716, 0.16717635, 0.13251784, 0.19571865]])